[package]
authors = ["Lance Hart <shipsimfan@hotmail.com>"]
edition = "2021"
name = "init"
version = "0.1.0"

[[bin]]
bench = false
doc = false
doctest = false
name = "init"
test = false

[dependencies]
base = { workspace = true }
uefi = { workspace = true }
acpi = { workspace = true }
