[package]
authors = ["Lance Hart <shipsimfan@hotmail.com>"]
edition = "2021"
name = "init"
version = "0.1.0"

[dependencies]
bootloader = { workspace = true }
log = { workspace = true }

[[bin]]
bench = false
doc = false
doctest = false
name = "init"
test = false
