[workspace]
default-members = ["kernel"]

members = [
  "acpi",
  "base",
  "device",
  "drivers/hpet",
  "drivers/uefi",
  "interrupts",
  "kernel",
  "memory",
  "process",
  "sessions",
  "time",
]
