[workspace]
default-members = ["kernel"]

members = [
  "acpi",
  "base",
  "device",
  "drivers/cmos",
  "drivers/fat32",
  "drivers/hpet",
  "drivers/ide",
  "drivers/pci",
  "drivers/uefi",
  "filesystem",
  "interrupts",
  "ipc",
  "kernel",
  "memory",
  "process",
  "process_types",
  "program_loader",
  "sessions",
  "time",
]
