[workspace]
default-members = ["init"]

members = ["base", "global_state", "init", "uefi", "acpi"]

[workspace.dependencies]
base = { path = "./base" }
global_state = { path = "./global_state" }
uefi = { path = "./uefi" }
acpi = { path = "./acpi" }
