[package]
authors = ["Lance Hart <shipsimfan@hotmail.com>"]
edition = "2021"
name = "interrupts"
version = "0.1.0"

[lib]
bench = false
crate-type = ["lib"]
doc = false
doctest = false
name = "interrupts"
test = false

[dependencies]
local_state = { workspace = true }
gdt = { workspace = true }
