[unstable]
build-std=["core","compiler_builtins", "alloc"]
build-std-features=["compiler-builtins-mem"]

[build]
target = "x86_64-los.json"
rustflags = ["-C", "link-args=-T link.ld", "-C", "code-model=medium", "-C", "relocation-model=static"]